name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Gradle Config
        run: |
          # Этот блок создает временный файл настроек, чтобы Gradle не искал папку app
          echo "include(':')" > settings.gradle.kts
          echo "apply plugin: 'com.android.application'" > build.gradle.kts

      - name: Build APK
        run: gradle assembleDebug --stacktrace
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: crypto-app-result
          path: "**/*.apk"
